config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/estudiante', to: 'estudiante#index'
  get 'static/home'
  get 'error/show'
  get 'error/no_disponible'
  get 'error/no_permiso'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}, :skip => [:sessions, :registrations, :passwords]
  as :user do
    get "/users/sign_in" => "error#no_permiso", :as => :new_user_session
    post "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end 
  resources :users, :only => [:edit, :update]
  get 'asignaturas/copy', to: 'asignaturas#copy'
  resources :asignaturas, :except => [:destroy] do
    resources :qcds do
      get '/answergroups/grupal' => 'answergroups#grupal' 
      resources :answergroups, :only => [:new, :create]
    end
  end
  root to: 'static#home'

end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
  belongs_to :user
  has_many :qcds, dependent: :destroy
  validates :nombre, presence: true, length: { minimum: 3, maximum: 400 }
  validates :nrc, presence: true, length: { minimum: 4, maximum: 4}
  validates :division,:dpto,:programa,:semestre,:creditos,:objetivo1, presence: true
  def self.search(nrc, semestre)
    where("nrc LIKE #{nrc}", "semestre LIKE #{semestre}")
  end
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_asignatura, only: [:show, :edit, :update, :destroy]
  
  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.where(user_id: current_user.id).order("semestre DESC")
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
    control_access
    @qcd = Qcd.where(asignatura_id: @asignatura.id)
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
    @date = listyear
  end
  
  def copy
    @origin = Asignatura.find(params[:id])
    @asignatura = Asignatura.new
    @asignatura.division = @origin.division
    @asignatura.dpto = @origin.dpto
    @asignatura.programa = @origin.programa
    @asignatura.nombre = @origin.nombre
    @asignatura.semestre = @origin.semestre
    @asignatura.creditos = @origin.creditos
    @asignatura.objetivo1 = @origin.objetivo1
    @asignatura.objetivo2 = @origin.objetivo2
    @asignatura.objetivo3 = @origin.objetivo3
    @asignatura.objetivo4 = @origin.objetivo4
    @asignatura.objetivo5 = @origin.objetivo5
    @asignatura.objetivo6 = @origin.objetivo6
    @asignatura.objetivo7 = @origin.objetivo7
    @asignatura.objetivo8 = @origin.objetivo8
    @asignatura.objetivo9 = @origin.objetivo9
    @asignatura.objetivo10 = @origin.objetivo10
    @asignatura.num_estud = @origin.num_estud
    @date = listyear
  end

  # GET /asignaturas/1/edit
  def edit
    @date = listyear
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to asignaturas_path, notice: 'Asignatura creada satisfactoriamente' }
        format.json { render :show, status: :created, location: @asignatura }
      else
        format.html { render :new }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaturas/1
  # PATCH/PUT /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to asignaturas_path, notice: 'Asignatura actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @asignatura }
      else
        format.html { render :edit }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: 'Asignatura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:user_id, :division, :dpto, :programa, :nombre, :nrc, :semestre, :creditos, :num_estud, :objetivo1, :objetivo2, :objetivo3, :objetivo4, :objetivo5, :objetivo6, :objetivo7, :objetivo8, :objetivo9, :objetivo10)
    end
    
    def control_access
      if !current_user
        return false
      end
      if current_user.id != @asignatura.user_id
        redirect_to error_no_permiso_path
        return false
      end
    end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_form.html.haml
= simple_form_for(@asignatura, validate: true) do |f|
  = f.error_notification
  .form-inputs
    = f.hidden_field :user_id, :value => current_user.id
    .row
      .col-xs-12.col-sm-12.col-md-6
        .panel.panel-info
          .panel-heading
            Información General de la Asignatura
          .panel-body
            = f.input :division, collection: [["Arquitectura, Urbanismo y Diseño", "Arquitectura, Urbanismo y Diseño"],["Ciencias Básicas", "Ciencias Básicas"],["Ciencias de la Salud", "Ciencias de la Salud"],["Derecho", "Ciencia Política y Relaciones Internacionales", "Derecho", "Ciencia Política y Relaciones Internacionales"],["Escuela de Negocios", "Escuela de Negocios"],["Humanidades y Ciencias Sociales", "Humanidades y Ciencias Sociales"],["Ingenierías", "Ingenierías"],["Instituto de Estudios en Educación", "Instituto de Estudios en Educación"],["Instituto de Idiomas", "Instituto de Idiomas"]], required: true, label: 'Division'
            = f.input :dpto, collection: [["ARQUITECTURA Y URBANISMO", "ARQUITECTURA Y URBANISMO"], ["COMUNICACION SOCIAL", "COMUNICACION SOCIAL"], ["CIENCIA  POLÍTICA Y REL. INTERN.", "CIENCIA  POLÍTICA Y REL. INTERN."], ["DERECHO", "DERECHO"] ,["DISEÑO", "DISEÑO"], ["ECONOMIA", "ECONOMIA"],["EDUCACION" , "EDUCACION"],["ENFERMERIA" , "ENFERMERIA"],["ESPAÑOL" , "ESPAÑOL"],["FINANZAS Y ORGANIZACIONES" , "FINANZAS Y ORGANIZACIONES"],["FISICA" , "FISICA"],["HISTORIA Y CIENCIAS SOCIALES" , "HISTORIA Y CIENCIAS SOCIALES"],["HUMANIDADES Y FILOSOFÍA" , "HUMANIDADES Y FILOSOFÍA"],["INGENIERÍA  CIVIL  Y  AMBIENTAL" , "INGENIERÍA  CIVIL  Y  AMBIENTAL"],["ELECTRICA Y ELECTRONICA" , "ELECTRICA Y ELECTRONICA"],["INGENIERIA INDUSTRIAL" , "INGENIERIA INDUSTRIAL"],["INGENIERIA MECANICA" , "INGENIERIA MECANICA"],["INGENIERIA DE SISTEMAS" , "INGENIERIA DE SISTEMAS"],["LENGUAS EXTRANJERAS" , "LENGUAS EXTRANJERAS"],["MATEMATICAS Y ESTADÍSTICA" , "MATEMATICAS Y ESTADÍSTICA"],["MEDICINA" , "MEDICINA"],["MERCADEO Y NEGOCIOS INTERNACIONALES" , "MERCADEO Y NEGOCIOS INTERNACIONALES"],["MÚSICA" , "MÚSICA"],["ODONTOLOGÍA" , "ODONTOLOGÍA"],["PSICOLOGIA" , "PSICOLOGIA"],["QUIMICA Y BIOLOGIA" , "QUIMICA Y BIOLOGIA"],["SALUD  PÚBLICA" , "SALUD  PÚBLICA"]]  ,required: true, label: 'Departamento', validate: { presence: true}
            = f.input :programa, collection:[["Administración de empresas","Administración de empresas"],["Arquitectura","Arquitectura"],["Ciencia Política y Gobierno","Ciencia Política y Gobierno"],["Comunicación Social y Periodismo","Comunicación Social y Periodismo"],["Contaduría Púbica","Contaduría Púbica"],["Derecho","Derecho"],["Diseño Gráfico","Diseño Gráfico"],["Diseño Industrial","Diseño Industrial"],["Economía","Economía"],["Enfermería","Enfermería"],["Filosofía y Humanidades","Filosofía y Humanidades"],["Geología","Geología"],["IngenieríaElectrónica","IngenieríaElectrónica"],["Ingeniería Civil","Ingeniería Civil"],["Ingeniería de Sistemas y Computación","Ingeniería de Sistemas y Computación"],["Ingeniería Eléctrica","Ingeniería Eléctrica"],["Ingeniería Industrial","Ingeniería Industrial"],["Ingeniería Mecánica","Ingeniería Mecánica"],["Licenciatura en Filosofía y Humanidades","Licenciatura en Filosofía y Humanidades"],["Licenciatura en Matemáticas","Licenciatura en Matemáticas"],["Licenciatura en Pedagogía Infantil","Licenciatura en Pedagogía Infantil"],["Matemáticas","Matemáticas"],["Medicina","Medicina"],["Música","Música"],["Negocios Internacionales","Negocios Internacionales"],["Odontología","Odontología"],["Psicología","Psicología"],["Relaciones Internacionales","Relaciones Internacionales"]], required: true, label: 'Programa'
            = f.input :nombre, input_html: { required: true }, label: 'Nombre de la Asignatura'
      .col-xs-12.col-sm-12.col-md-6
        .panel.panel-info
          .panel-heading
            Información Detallada de la Asignatura
          .panel-body
            = f.input :nrc, required: true, label: 'NRC', validate: { presence: true}
            = f.input :semestre, collection: @date, required: true, label: 'Semestre', validate: { presence: true }
            = f.input :creditos, required: true, label: 'Numero de Creditos'
            = f.input :num_estud, required: true, label: 'Numero de Estudiantes'
    .panel.panel-info
      .panel-heading
        Resultados de aprendizaje 
      .panel-body
        %p
          A continuación, escriba los resultados de aprendizaje que se han trabajado hasta ahora en su curso. Procure redactarlos de forma clara y específica para que el estudiante los comprenda fácilmente, puesto que éste deberá evaluarlos durante la implementación del QCD.
        %p
          No es necesario que llene todos los espacios, solo el número de resultados de aprendizaje que usted considere trabajados hasta ahora.
        = f.input :objetivo1, required: true, label: 'Resultado de aprendizaje 1', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo2, label: 'Resultado de aprendizaje 2', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo3, label: 'Resultado de aprendizaje 3', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo4, label: 'Resultado de aprendizaje 4', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo5, label: 'Resultado de aprendizaje 5', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo6, label: 'Resultado de aprendizaje 6', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo7, label: 'Resultado de aprendizaje 7', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo8, label: 'Resultado de aprendizaje 8', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo9, label: 'Resultado de aprendizaje 9', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
        = f.input :objetivo10, label: 'Resultado de aprendizaje 10', :input_html => {"data-toggle" => "tooltip", "data-placement" => "top", "title" => "Ejemplo: \nIdentificar los diferentes tipos de escalas de medición en el diseño de planos arquitectónicos."}
  .form-actions.text-left
    = f.button :submit, value: "Enviar"
    

app/views/asignaturas/copy.html.haml
%h1.text-center
    %legend Nuevo Curso

= render 'form'

app/views/asignaturas/edit.html.haml
%h1.text-center
    %legend Editar Curso

= render 'form'

app/views/asignaturas/index.html.haml
.row
  .col-xs-12.col-sm-6
    %h1 Cursos:
  .col-xs-12.col-sm-6.text-center
    %br
    = link_to 'Agregar Curso', new_asignatura_path, class: "btn btn-primary"
    %br
%br
- @asignaturas.group_by{|h| h[:semestre]}.each_with_index do |asignatura,index|
  .panel.panel-default
    .panel-heading
      %a
        =asignatura[0]
        <span class="pull-right"><i class="glyphicon glyphicon-chevron-down"></i></span>
    %ul.list-group.collapse{:id => "item_#{index}"}
      -asignatura[1].each do |temp|
        %li.list-group-item
          .row
            .col-xs-12.col-sm-6.col-md-5
              %p
                %b Nombre:
                =temp.nombre
            .col-xs-12.col-sm-6.col-md-2
              %p
                %b NRC:
                =temp.nrc
            .col-xs-12.col-sm-10.col-md-4.col-sm-offset-1.col-md-offset-1
              .btn-group-vertical.btn-group-justified
                =link_to 'Editar', edit_asignatura_path(temp), html_options = {class: "btn  btn-sm btn-default"}
                =link_to 'Ver QCD', asignatura_path(temp), html_options = {class: "btn  btn-sm btn-default"}
                =link_to 'Copiar', asignaturas_copy_path(:id => temp), html_options = {class: "btn  btn-sm btn-default"}
:javascript
  $(document).on('click touchstart', '.panel-heading', function(e){
      var $this = $(this);
      console.log($this.parents('.panel').find('.list-group'));
  	if(!$this.parents('.panel').find('.list-group').hasClass('collapse')) {
  		$this.parents('.panel').find('.list-group').slideUp();
  		$this.parents('.panel').find('.list-group').addClass('collapse');
  		$this.find('i').removeClass('glyphicon-chevron-up').addClass('glyphicon-chevron-down');
  	} else {
  		$this.parents('.panel').find('.list-group').slideDown();
  		$this.parents('.panel').find('.list-group').removeClass('collapse');
  		$this.find('i').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
  	}
  })

app/views/asignaturas/new.html.haml
%h1 Nuevo Curso

= render 'form'

app/views/asignaturas/show.html.haml
.well
    .row
        .col-xs-12.col-sm-6.col-md-12
            %p
                %b Nombre:
                = @asignatura.nombre
        .col-xs-12.col-sm-6.col-md-2
            %p
                %b Nrc:
                = @asignatura.nrc
        .col-xs-12.col-sm-6.col-md-4
            %p
                %b Semestre:
                = @asignatura.semestre
        .col-xs-12.col-sm-6.col-md-4
            %p
                %b Numero de Estudiantes:
                = @asignatura.num_estud
%br
%button.btn.btn-primary{"data-target" => "#qcdForm", "data-toggle" => "modal", :type => "button"}
    Agregar QCD
#qcdForm.modal.fade{"aria-labelledby" => "qcdFormLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
        .modal-content
            .modal-header
                %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                    %span{"aria-hidden" => "true"} ×
                %h4#qcdFormLabel.modal-title Agregar QCD al Curso
            .modal-body
                %h5 Recuerde ingresar información real de la asignatura, el QCD se aplica en una hora de la clase 
                %p Ingrese la Fecha tentativa en la que esperaria realizar el QCD. 
                %b Fecha y Hora Tentativa:
                #datetimepicker1.input-group.date
                    %input.form-control{:type => "text", :name => "fecha", :id => "fecha"}/
                    %span.input-group-addon
                        %span.glyphicon.glyphicon-calendar
                :javascript
                    $(function () {
                        var minDateVal = new Date();
                        minDateVal.setDate(minDateVal.getDate() + 2);
                        var maxDateVal = new Date();
                        maxDateVal.setDate(maxDateVal.getDate() + 30);
                        $('#datetimepicker1').datetimepicker({
                            sideBySide: true,
                            minDate: minDateVal,
                            maxDate: maxDateVal
                        });
                    });
                %p 
                    %b Salon de Clase:
                    %input.form-control{:type => "text", :name => "salon", :id => "salon",:placeholder => "Numero - Bloque"}
            .modal-footer
                %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cerrar
                %button.btn.btn-primary{:type => "button", :id  => "btn1"} Agregar
                :javascript
                      $("#btn1").click(function(){
                        $('#btn1').prop('disabled', true);
                        $.ajax({
                          type: "POST",
                          url: "/asignaturas/#{@asignatura.id}/qcds",
                          data: {fecha: new $("#fecha").val(), salon: $('#salon').val() } ,
                          success: function(data) {
                            location.reload();
                          },
                          failure: function() {
                            alert("Ha ocurrido un error por favor vuelva a intentarlo mas tarde.");
                          }
                        })})
%br
%br
.list-group
    - @qcd.each do |qcd|
        .list-group-item  
            -if qcd != nil
                -if qcd.estados == "En Espera de Aprobacion" or qcd.estados == "No Aprobado" or qcd.estados == "Revision"
                    .row
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Fecha:
                                = qcd.fecha != nil ? qcd.fecha.strftime("%F %I:%M %P") : "Error"
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Salon:
                                = qcd.salon != nil ? qcd.salon : "Error"
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Estado:
                                = qcd.estados
                -if qcd.estados == "Aprobado" 
                    .row
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Fecha:
                                = qcd.fecha != nil ? qcd.fecha.strftime("%F %I:%M %P") : "Error"
                        .col-xs-12.col-sm-6.col-lg-8
                            %p
                                %b Salon:
                                = qcd.salon != nil ? qcd.salon : "Error"
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Estado:
                                = qcd.estados
                        .col-xs-12.col-sm-6.col-lg-4
                            .btn-group.btn-group-justified
                                =link_to 'Actividad Individual', new_asignatura_qcd_answergroup_path(@asignatura, qcd), html_options = {class: "btn  btn-sm btn-default"}
                                =link_to 'Actividad Grupal', asignatura_qcd_answergroups_grupal_path(@asignatura, qcd), html_options = {class: "btn  btn-sm btn-default"}
                -if qcd.estados == "Terminado"
                    .row
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Fecha:
                                = qcd.fecha != nil ? qcd.fecha.strftime("%F %I:%M %P") : "Error"
                        .col-xs-12.col-sm-6.col-lg-8
                            %p
                                %b Salon:
                                = qcd.salon != nil ? qcd.salon : "Error"
                        .col-xs-12.col-sm-6.col-lg-4
                            %p
                                %b Estado:
                                = qcd.estados
                        .col-xs-12.col-sm-6.col-lg-8
                            %p
                                %b Informe:
                                = link_to 'Resultados', asignatura_qcd_path(@asignatura, qcd), html_options = {class: "btn  btn-sm btn-default"}