config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/estudiante', to: 'estudiante#index'
  get 'static/home'
  get 'error/show'
  get 'error/no_disponible'
  get 'error/no_permiso'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}, :skip => [:sessions, :registrations, :passwords]
  as :user do
    get "/users/sign_in" => "error#no_permiso", :as => :new_user_session
    post "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end 
  resources :users, :only => [:edit, :update]
  get 'asignaturas/copy', to: 'asignaturas#copy'
  resources :asignaturas, :except => [:destroy] do
    resources :qcds do
      get '/answergroups/grupal' => 'answergroups#grupal' 
      resources :answergroups, :only => [:new, :create]
    end
  end
  root to: 'static#home'

end

app/controllers/estudiante_controller.rb
class EstudianteController < ApplicationController
  def index
      @date = listyear
      if params[:nrc] and params[:semestre]
        @asignatura = Asignatura.where(:nrc => params[:nrc], :semestre => params[:semestre])
        @qcds = Qcd.where(:asignatura_id => @asignatura.ids, :estados => 1)
      end
  end
end

app/helpers/estudiante_helper.rb
module EstudianteHelper
end

app/views/estudiante/index.html.haml
= form_tag(estudiante_path, :method => "get", id: "search-form") do
  .row
    .col-xs-12.col-sm-6.col-md-4.col-lg-3
      %br
      .input-group 
        %span.input-group-addon
          %b NRC:
        = text_field_tag :nrc, params[:nrc], placeholder: "NRC de la asignatura", class: "form-control",:required => true
    .col-xs-12.col-sm-6.col-md-4.col-lg-3
      %br 
      .input-group 
        %span.input-group-addon
          %b Semestre:
        = select_tag(:semestre, options_for_select(@date), {:class => 'form-control', :name => :semestre})
        // = text_field_tag :semestre, params[:semestre], placeholder: "Semestre Academico", class: "form-control"
    .col-xs-12.col-sm-12.col-md-4.col-lg-2.text-center
      %br
      = submit_tag "Buscar", class: "btn btn-primary"
    
- if params[:nrc] and params[:semestre]
  - if @qcds.present?
    = render @qcds
  - else
    %br
    %br
    %h4 
      No hay QCD disponible con 
      %b NRC:
      #{params[:nrc]} y 
      %b semestre
      #{params[:semestre]}.